# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|

  # Provisioning for Master server
  config.vm.define "Master" do |master|
    master.vm.box = "ubuntu/focal64"
    master.vm.hostname = "Master"
    master.vm.network "private_network", ip: "192.168.33.10"
    master.vm.provider "virtualbox" do |vb|
      vb.memory = "1024"
      vb.cpus = 1
    end
    master.vm.provision "shell", inline: <<-SHELL
      # Update and install necessary packages
      sudo apt-get update
      sudo apt-get install -y apache2
    SHELL
#    config.ssh.private_key_path = "~/.ssh/id_rsa"
  end

  # Provisioning for Slave server
  config.vm.define "Slave" do |slave|
    slave.vm.box = "ubuntu/focal64"
    slave.vm.hostname = "Slave"
    slave.vm.network "private_network", ip: "192.168.33.11"
    slave.vm.provider "virtualbox" do |vb|
      vb.memory = "1024"
      vb.cpus = 1
    end
    slave.vm.provision "shell", inline: <<-SHELL
      # Update and install necessary packages
      sudo apt-get update
      sudo apt-get install -y apache2
    SHELL
#    config.ssh.private_key_path = "~/.ssh/id_rsa"
  end

end
